### ISSUE TITLE
Anyone developing on this project? It's too good to abandon IMO.

### ISSUE THREAD

**Issue by nmcgann** [kaore/CibulCalendar#20]
This is a convincing js-only simple calendar and doesn't take much bug fixing and extending to be very useful. It also minimizes small if the multi-langage stuff is removed from the core. (15.2k before gzipping after my mods were added and ~5k gzipped!)

I've:
- fixed the obvious bugs in the other issues (the Feb 2016 and related things)
- added year prev/next buttons
- modified the factory (`setCibulCalendar`) to instantiate immediately and return the calendar object so methods like `setSelected` can be called on it. (rather than instantiate the object via `new CibulCalendar` in a div which is awkward to integrate).
- modified the `_init ` method to update the input field value and fire `change` if there is a `selected` option.
- fixed the basic css up a bit (z-index etc.)

Looks like this with the year buttons added and a bit of css tweaking:
![cibulcalc_pic_after](https://cloud.githubusercontent.com/assets/6752320/11563258/fa544444-99ca-11e5-9fb8-396ca6cad5b1.jpg)

It's not fancy, but for a simple calendar it's a lot less js and css to load than any of the jQuery-based alternatives.

It would be great if it could be revived by someone that is expert in js and fixed/extended properly?

**Comment by kaore** [comment]
Hi, I'll have a look shortly. Thanks for your contribution

**Comment by nmcgann** [comment]
Hi kaore - great that the owner is still watching it!

I needed a js-only calendar to revive a project from 2008 that used the YUI calendar widget and no other js framework. The YUI calendar is a bit broken in modern browsers and almost all the alternatives needed jQuery+jQuery UI which is crazy just to do a calendar, I was going to be loading 360k of compressed js+css for one function.

**Comment by nmcgann** [comment]
I included my various fixes and changes in a fork: https://github.com/nmcgann/CibulCalendar.

Has some comments in the `readme` listing the changes and a `.html` demo file to show the ideas.

There are all sorts of things that could possibly be added, but the only thing I think really needs doing is a callback option to allow the date format inserted into the input field to be easily changed (currently via `_dateToString`). The `dd/mm/yyyy` format works fine for me, but I can see people wanting alternatives.

**Comment by kaore** [comment]
Hi, @nmcgann, thanks for your work, I added you as a collaborator of this project
